version: '3'

services:
  postgresql:
    image: postgres:12
    container_name: "fastapi_chat_postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    container_name: "fastapi_chat_app"
    restart: always
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8002:8000"
    volumes:
      - ./files/:/app/files/
      - ./data/:/app/data/

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./docker-compose/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    user: root
    restart: always
    ports:
      - "3421:3000"
    volumes:
      - ./docker-compose/grafana-data/data:/var/lib/grafana
      - ./docker-compose/grafana-data/certs:/certs
      - ./docker-compose/grafana/provisioning:/etc/grafana/provisioning
      - ./docker-compose/grafana/dashboards:/var/lib/grafana/dashboards
    env_file:
      - .env
