{
 "title": "API чата",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Все HTTP запросы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(total_request_total[60s])",
     "legendFormat": "Всего HTTP запросов"
    }
   ]
  },
  {
   "title": "Сообщения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(get_all_messages_total[60s])",
     "legendFormat": "Все сообщения"
    },
    {
     "expr": "increase(get_chat_messages_total[60s])",
     "legendFormat": "Сообщения чата"
    },
    {
     "expr": "increase(change_message_text_total[60s])",
     "legendFormat": "Изменения текста"
    },
    {
     "expr": "increase(delete_message_total[60s])",
     "legendFormat": "Удаление сообщения"
    }
   ]
  },
  {
   "title": "Авторизация",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(registration_total[60s])",
     "legendFormat": "Регистрация"
    },
    { "expr": "increase(login_total[60s])", "legendFormat": "Вход" },
    {
     "expr": "increase(refresh_tokens_total[60s])",
     "legendFormat": "Обновление токенов"
    },
    {
     "expr": "increase(logout_total[$__rate_interval])",
     "legendFormat": "Выход"
    }
   ]
  },
  {
   "title": "Участники чата",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(get_chat_members_total[60s])",
     "legendFormat": "Запрос участников чата"
    },
    {
     "expr": "increase(add_chat_member_total[60s])",
     "legendFormat": "Добавление участника"
    },
    {
     "expr": "increase(delete_chat_member_total[60s])",
     "legendFormat": "Удаление участника"
    }
   ]
  },
  {
   "title": "Пользователи",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(change_user_data_total[60s])",
     "legendFormat": "Изменение данных"
    },
    {
     "expr": "increase(upload_avatar_total[60s])",
     "legendFormat": "Загрузка аватара"
    },
    {
     "expr": "increase(get_login_avatar_file_total[60s])",
     "legendFormat": "Файл аватара"
    },
    {
     "expr": "increase(get_login_avatar_filename_total[60s])",
     "legendFormat": "Название файла аватара"
    },
    {
     "expr": "increase(get_user_info_total[$__rate_interval])",
     "legendFormat": "Информация"
    }
   ]
  },
  {
   "title": "Контакты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(get_contacts_total[$__rate_interval])",
     "legendFormat": "Список контактов"
    },
    {
     "expr": "increase(create_contact_total[$__rate_interval])",
     "legendFormat": "Создание контакта"
    },
    {
     "expr": "increase(delete_contact_total[$__rate_interval])",
     "legendFormat": "Удаление контакта"
    },
    {
     "expr": "increase(get_contact_info_total[$__rate_interval])",
     "legendFormat": "Данные контакта"
    },
    {
     "expr": "increase(change_contact_total[$__rate_interval])",
     "legendFormat": "Изменение контакта"
    }
   ]
  },
  {
   "title": "Чаты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(create_new_chat_total[60s])",
     "legendFormat": "Создание чата"
    },
    {
     "expr": "increase(change_chat_name_total[$__rate_interval])",
     "legendFormat": "Изменение названия"
    }
   ]
  }
 ]
}