{
 "title": "API чата",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Все HTTP запросы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(total_request_total[60s])",
     "legendFormat": "Всего HTTP запросов"
    }
   ]
  },
  {
   "title": "Все WS сообщения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(total_ws_messages_total[60s])",
     "legendFormat": "Всего"
    },
    {
     "expr": "increase(in_ws_messages_total[60s])",
     "legendFormat": "Входящие"
    },
    {
     "expr": "increase(out_ws_messages_total[60s])",
     "legendFormat": "Исходящие"
    }
   ]
  },
  {
   "title": "Входящие WS сообщения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(start_typing_in_ws_message_total[60s])",
     "legendFormat": "Начало печатания"
    },
    {
     "expr": "increase(stop_typing_in_ws_message_total[60s])",
     "legendFormat": "Окончания печатания"
    },
    {
     "expr": "increase(text_in_ws_message_total[60s])",
     "legendFormat": "Текстовое сообщение"
    },
    {
     "expr": "increase(read_message_in_ws_message_total[60s])",
     "legendFormat": "Прочтение сообщения"
    }
   ]
  },
  {
   "title": "Исходящие WS сообщения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(online_status_out_ws_message_total[60s])",
     "legendFormat": "Вход"
    },
    {
     "expr": "increase(ofline_status_out_ws_message_total[60s])",
     "legendFormat": "Выход"
    },
    {
     "expr": "increase(start_typing_out_ws_message_total[60s])",
     "legendFormat": "Старт печатания"
    },
    {
     "expr": "increase(stop_typing_out_ws_message_total[60s])",
     "legendFormat": "Окончание печатания"
    },
    {
     "expr": "increase(text_out_ws_message_total[60s])",
     "legendFormat": "Текст"
    },
    {
     "expr": "increase(add_chat_member_out_ws_message_total[$__rate_interval])",
     "legendFormat": "Добавление пользователя к чату"
    },
    {
     "expr": "increase(delete_chat_member_out_ws_message_total[$__rate_interval])",
     "legendFormat": "Удаление пользователя из чата"
    },
    {
     "expr": "increase(change_chat_name_out_ws_message_total[$__rate_interval])",
     "legendFormat": "Изменение названия чата"
    },
    {
     "expr": "increase(change_message_text_out_ws_message_total[$__rate_interval])",
     "legendFormat": "Изменение текста сообщения"
    },
    {
     "expr": "increase(delete_message_out_ws_message_total[60s])",
     "legendFormat": "Удалении сообщения"
    },
    {
     "expr": "increase(info_out_ws_message_total[60s])",
     "legendFormat": "Информационное сообщение"
    },
    {
     "expr": "increase(new_chat_out_ws_message_total[60s])",
     "legendFormat": "Новый чат"
    }
   ]
  },
  {
   "title": "Авторизация",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(registration_total[60s])",
     "legendFormat": "Регистрация"
    },
    { "expr": "increase(login_total[60s])", "legendFormat": "Вход" },
    {
     "expr": "increase(refresh_tokens_total[60s])",
     "legendFormat": "Обновление токенов"
    },
    {
     "expr": "increase(logout_total[$__rate_interval])",
     "legendFormat": "Выход"
    }
   ]
  },
  {
   "title": "Сообщения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(get_all_messages_total[60s])",
     "legendFormat": "Все сообщения"
    },
    {
     "expr": "increase(get_chat_messages_total[60s])",
     "legendFormat": "Сообщения чата"
    },
    {
     "expr": "increase(change_message_text_total[60s])",
     "legendFormat": "Изменения текста"
    },
    {
     "expr": "increase(delete_message_total[60s])",
     "legendFormat": "Удаление сообщения"
    }
   ]
  },
  {
   "title": "Пользователи",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(change_user_data_total[60s])",
     "legendFormat": "Изменение данных"
    },
    {
     "expr": "increase(upload_avatar_total[60s])",
     "legendFormat": "Загрузка аватара"
    },
    {
     "expr": "increase(get_login_avatar_file_total[60s])",
     "legendFormat": "Файл аватара"
    },
    {
     "expr": "increase(get_login_avatar_filename_total[60s])",
     "legendFormat": "Название файла аватара"
    },
    {
     "expr": "increase(get_user_info_total[$__rate_interval])",
     "legendFormat": "Информация"
    }
   ]
  },
  {
   "title": "Участники чата",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(get_chat_members_total[60s])",
     "legendFormat": "Запрос участников чата"
    },
    {
     "expr": "increase(add_chat_member_total[60s])",
     "legendFormat": "Добавление участника"
    },
    {
     "expr": "increase(delete_chat_member_total[60s])",
     "legendFormat": "Удаление участника"
    }
   ]
  },
  {
   "title": "Чаты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(create_new_chat_total[60s])",
     "legendFormat": "Создание чата"
    },
    {
     "expr": "increase(change_chat_name_total[$__rate_interval])",
     "legendFormat": "Изменение названия"
    }
   ]
  },
  {
   "title": "Контакты",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(get_contacts_total[$__rate_interval])",
     "legendFormat": "Список контактов"
    },
    {
     "expr": "increase(create_contact_total[$__rate_interval])",
     "legendFormat": "Создание контакта"
    },
    {
     "expr": "increase(delete_contact_total[$__rate_interval])",
     "legendFormat": "Удаление контакта"
    },
    {
     "expr": "increase(get_contact_info_total[$__rate_interval])",
     "legendFormat": "Данные контакта"
    },
    {
     "expr": "increase(change_contact_total[$__rate_interval])",
     "legendFormat": "Изменение контакта"
    }
   ]
  }
 ]
}